version: "3.8"
volumes:
    logs:
        driver: local
services: 
    spring:
        container_name: chatapp_spring 
        image: chatapp
        ports: 
          - "5780:8080"
        depends_on:
          - database 
        build:
            dockerfile: Dockerfile
            context: .
            args: 
              ENVIRONMENT: ${ENV}
              MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
              MYSQL_USER: "user"
              MYSQL_PASSWORD: ${PASSWORD}
              MYSQL_DATABASE: "chatapp"

    database:
        container_name: chatapp_db
        image: mariadb:10.8.2
        ports: 
           - "5781:3306"
        environment:
           MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
           MYSQL_USER: "user"
           MYSQL_PASSWORD: ${PASSWORD}
           MYSQL_DATABASE: "chatapp"     
       
    adminer:
        container_name: chatapp_adminer
        image: adminer:latest
        restart: always
        ports:
           - "5782:8080"
