spring:
  config:
    activate:
      on-profile: prod
    import: optional:secrets.properties
  jpa:
    hibernate:
      ddl-auto: update
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    username: user
    password: 1234
    url: jdbc:mariadb://localhost:3306/chat_app_V2