spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/chat_app_v2
    username: user
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mariadb://185.8.165.101:5781/chatapp?useSSL=false
    username: root
    password: tajneheslo2012
  jpa:
    hibernate:
      ddl-auto: update